// <auto-generated />
namespace TodoListManagement.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class atualizadoonomedecoluna : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(atualizadoonomedecoluna));
        
        string IMigrationMetadata.Id
        {
            get { return "201503041733169_atualizado o nome de coluna"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
